options(warn = -1) # suppress all warning messages generated by R


header = dashboardHeader(title = h2(strong("Pune Municipal Expenditure Analysis"),align="center"), titleWidth = 1725)

# Customizing Side-Bar Options and Drop Downs
sidebar = dashboardSidebar(disable = TRUE)

# Customizing Main-Panel and Outputs of the Dashboard
body = dashboardBody(
  
  # ~ Creates a logo for browser-tab.
  tags$head(
    tags$link(rel = "shortcut icon", href = "logo.jpg")),
  
  # ~ Restricts display of error on the Dashboard. Output will be blank in case of error
  # @ Disable if you wish to see errors while developing the dashboards.
  tags$style(type="text/css", ".shiny-output-error { visibility: hidden; }", 
             ".shiny-output-error:before { visibility: hidden; }"),
  ####
  
  # Define UI for random distribution app ----
  fluidPage(
    
    # App title ----
    titlePanel(h3(strong("Municipal Region"),align="left")),
    
    # Sidebar layout with input and output definitions ----
    sidebarLayout(
      
      # Sidebar panel for inputs ----
      sidebarPanel(
        
        # Input: Select the random distribution type ----
        radioButtons("Region", "Region:",
                     c("Kothrud" = "kothrud",
                       "Sinhgad Road" = "sinhgad",
                       "Kasba"="kasba",
                       "Bibwewadi"="bibwewadi",
                       "Yerawda"="yerawda")),
        
       # br() element to introduce extra vertical spacing ----
      br(),
      
      
      selectInput(inputId = "Year",
                  label = "Year:",
                  choices=unique(kothrud$Year), selected="17-18"),width = 3
      
      
      
      
        # 
        # # Input: Slider for the number of observations to generate ----
        # sliderInput("n",
        #             "Number of observations:",
        #             value = 500,
        #             min = 1,
        #             max = 1000)
        
      ),
      
      # Main panel for displaying outputs ----
      mainPanel(
        
        # Output: Tabset w/ plot, summary, and table ----
        tabsetPanel(type = "tabs",
                    tabPanel(strong("Plot"),h2("Yearwise",align="center"),plotOutput("hist"),h2("Expenditure",align="center"),plotOutput("bar")),
                    tabPanel(strong("Summary"),h2(strong("Summary of Total Expenses"),align = "center"),verbatimTextOutput("summary")),
                    tabPanel(strong("Conclusion"),br(),h4(strong("Visualizing taxpayer money spent by authorities can help combat corruption and promote transparency in government bodies. This information helps the public understand welfare allocation and trust elected officials, enabling effective governance. A clear visualization of governmental spending acts as a watchdog, ensuring transparency and accountability."
                                                     )))
                   
  
                              
        
      )
    )
  ),
)
)

  
  
  ####
  # tabBox(id = "tabs", height = NULL , width = 13,
  #        
  #        # Home Tab for Inputs
  #        tabPanel( id="tab1",
  #                  title = strong("Tab 1"), status = "primary",
  #                  height = NULL , width = 12,
                   
                   #
         #           fluidRow(box(
         #                plotOutput("hist")
         #              )),
         #           
         #           
         #           fluidPage(
         #             
         #             titlePanel("Yearwise Expenditure"),
         #             
         #             sidebarLayout(
         #               
         #               sidebarPanel(
         #                 selectInput(inputId = "Year",
         #                             label = "Year:",
         #                             choices=unique(kothrud$Year), selected="17-18"),width = 3
         #               ),
         #               
         #               mainPanel(
         #                 plotOutput("bar"),width = 9
         #               )
         #             )
         #           )
         #           
          

# Final Step for building the UI
dashboardPage(header, sidebar, body, skin = "purple", title = "Nagarsevak in Kothrod")
